"""create_login_record_table

Revision ID: 150028c2e9ba
Revises: ad8b052288e
Create Date: 2014-11-21 15:07:56.164049

"""

# revision identifiers, used by Alembic.
revision = '150028c2e9ba'
down_revision = 'ad8b052288e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=40), nullable=False),
    sa.Column('ip_address', sa.String(length=20), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_record_account'), 'login_record', ['account'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_login_record_account'), table_name='login_record')
    op.drop_table('login_record')
    ### end Alembic commands ###
