"""added service column on talk

Revision ID: 2580654e242f
Revises: 2d5e42986e62
Create Date: 2013-09-21 17:30:54.667792

"""

# revision identifiers, used by Alembic.
revision = '2580654e242f'
down_revision = '2d5e42986e62'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talk', sa.Column('service', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talk', 'service')
    ### end Alembic commands ###
