"""create failed_login table

Revision ID: 460decade180
Revises: 5207ac0baea2
Create Date: 2013-09-12 16:01:52.642814

"""

# revision identifiers, used by Alembic.
revision = '460decade180'
down_revision = '5207ac0baea2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('ip_address', sa.String(length=20), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('failed_login')
    ### end Alembic commands ###
