"""updated user and article relationship

Revision ID: 5207ac0baea2
Revises: 1f38da2d56a1
Create Date: 2013-09-10 17:23:22.779335

"""

# revision identifiers, used by Alembic.
revision = '5207ac0baea2'
down_revision = '1f38da2d56a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
