"""fix typo slat to salt

Revision ID: a878ea881e5
Revises: 4702d2355ade
Create Date: 2013-06-17 16:35:38.797775

"""

# revision identifiers, used by Alembic.
revision = 'a878ea881e5'
down_revision = '4702d2355ade'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('salt', sa.String(length=16), nullable=False))
    op.drop_column('user', u'slat')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(u'slat', sa.VARCHAR(length=16), nullable=False))
    op.drop_column('user', 'salt')
    ### end Alembic commands ###
