"""remove salt column from user table, using bcrypt

Revision ID: ad8b052288e
Revises: 2580654e242f
Create Date: 2014-04-14 23:23:57.222861

"""

# revision identifiers, used by Alembic.
revision = 'ad8b052288e'
down_revision = '2580654e242f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_failed_login_username', 'failed_login', ['username'], unique=False)
    op.drop_column('user', 'salt')
    op.drop_column('user', 'notify_to_email')
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_username', table_name='user')
    op.drop_index('ix_user_email', table_name='user')
    op.add_column('user', sa.Column('notify_to_email', sa.BOOLEAN(), nullable=True))
    op.add_column('user', sa.Column('salt', sa.VARCHAR(length=16), nullable=False))
    op.drop_index('ix_failed_login_username', table_name='failed_login')
    ### end Alembic commands ###
